In [2]:
import numpy as np
x = np.array([1, 2, 3],dtype=np.float32)
print(x)
print(x.itemsize)

[1. 2. 3.]
4


In [3]:
np.sin(x)

array([0.841471 , 0.9092974, 0.14112  ], dtype=float32)

In [4]:
from math import sin
[sin(i) for i in x]

[0.8414709848078965, 0.9092974268256817, 0.1411200080598672]

In [ ]:
x = np.array([ [1,2,3],[4,5,6] ])
print(x)
x.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

In [8]:
print(x[:,0]) # 0th column
print(x[:,1]) # 1st column
print(x[0,:]) # 0th row
print(x[1,:]) # 1st row

[1 4]
[2 5]
[1 2 3]
[4 5 6]
